In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [17]:
import numpy as np

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [31]:
# 1
A = np.array([1,3,5,7,9,11,13,15,17,19,21])
A.shape                     # .shape is used to indicate the dimension of the array , (row,column)

(11,)

In [41]:
#2
B = np.array ([[1,3,17,7,9,11]])
B.max()                     # .max() is a method used to specified the maximum value of the array

np.int64(17)

In [42]:
#3
C = np.array ([1,3,5,11,9,7])
np.max(C)                     # np.max is used to target specific array to get their maximum value

np.int64(11)

In [60]:
#B
B = np.full((5,5),1)  # the (5,5) indicate that it's a 5x5 array and the 1 is the value use to fill the array
print(B.shape, '\n')  #is used to print the shape of the array B
print(B.size,'\n')    #is used to prints the size of the array B
print(B.ndim,'\n')    #is used to print the dimension of array B
print(B)              #is used to print the value of B

(5, 5) 

25 

2 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [44]:
#C
C = np.arange(-5, 6)          # arange stops before the end value, so the range (-5 , 6) starts at -5 but ends at 5

print("Array from -5 to +5:")
print(C)


value = C * 2 # Multiply number by 2

print("\nMultiplying each value by 2:")
print(value)

Array from -5 to +5:
[-5 -4 -3 -2 -1  0  1  2  3  4  5]

Multiplying each value by 2:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
